### PR TITLE
Beautify ALL the things!

### PR DESCRIPTION
**Pull request by rodrigomaia17**
adding js-beautify and applying it! 

=DD

### CODE REVIEW

**Comment by rodrigomaia17** [comment]
@enzoz @barboza What do you guys think?

**Comment by enzoz** [comment]
This is nice, it'll help us get close to an standardized code base.

**Comment by barboza** [comment]
Nice!
:ship: :it:

**Comment by rodrigomaia17** [comment]
@enzoz @barboza  sooooo, lets ~~~merrrgear~~~?

image

**Comment by enzoz** [comment]
Done! :rocket:

**Pull request merged**
